CC=g++
RES=windres

CFLAGS= -I/usr/local/include
LDFLAGS= -L/usr/local/lib -mno-cygwin  -mwindows -lddraw -ldinput -ldsound -ldxguid -luser32 -lgdi32 -lwsock32 -lwinmm

FLIST= MasterMain.cpp Masterx.cpp game.cpp start.cpp intro.cpp scores.cpp




all:
	$(RES) mp.rc -o rez.o	
	$(CC) $(CFLAGS) $(FLIST) rez.o $(LDFLAGS) -o mp2000.exe
clean:
	rm -rf *.o *~
 
