
CC=i586-mingw32msvc-g++
CFLAGS= -I/usr/local/i586-mingw32/include
LDFLAGS= -L/usr/local/i586-mingw32/lib -mwindows -lddraw -ldinput -ldsound -ldxguid -luser32 -lgdi32 -lwsock32 -lwinmm

FLIST= MasterMain.cpp Masterx.cpp



all:
	$(CC) $(CFLAGS) $(FLIST) $(LDFLAGS) -o mxtest.exe
clean:
	rm -rf *.o *~

