
CC=g++
CFLAGS= -I/usr/local/include
LDFLAGS= -L/usr/local/lib -mno-cygwin -mwindows -lddraw -ldinput -ldsound -ldxguid -luser32 -lgdi32 -lwsock32 -lwinmm

FLIST= MasterMain.cpp masterx.cpp

all:
	$(CC) $(CFLAGS) $(FLIST) $(LDFLAGS) -o mxtest.exe
clean:
	rm -rf *.o *~

 
