CC=i586-mingw32msvc-g++
CXXFLAGS= -I/usr/local/i586-mingw32/include
LDFLAGS= -L/usr/local/i586-mingw32/lib -mwindows -lddraw -ldinput -ldsound -ldxguid -luser32 -lgdi32 -lwsock32 -lwinmm

FILES=MasterMain.cpp masterx.cpp MasterConsole.cpp

all:
	$(CC) $(CXXFLAGS) $(FILES) -o MasterConsole.exe  $(LDFLAGS)
clean:
	rm -rf *.o *~
