
CC=i586-mingw32msvc-g++
RES=i586-mingw32msvc-windres
CFLAGS= -I/usr/local/i586-mingw32/include
LDFLAGS= -L/usr/local/i586-mingw32/lib -mwindows -lddraw -ldinput -ldsound -ldxguid -luser32 -lgdi32 -lwsock32 -lwinmm

FLIST= tictactoe.cpp masterx.cpp
LIBS=tictactoe.o rez.o masterx.o


all:
	$(RES)  Script1.rc -o rez.o
	$(CC) $(CFLAGS) $(FLIST) -c
	$(CC) $(LIBS)  $(LDFLAGS)  -o tictactoe.exe
clean:
	rm -rf *.o *~